name: Hugo build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.80.0'

      - name: Build
        run: hugo --minify
      
#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         env:
#           GCLOUD_API_KEY: ${{ secrets.GCLOUD_API_KEY }}



